-- A short, catchy display name for a listing (e.g. "The Cozy Koramangala Corner"),
-- distinct from its factual title. Generated by extraction, or templated for manual entries.
alter table listings add column if not exists nickname text;
